# fly.toml app configuration file generated for shepherd-ai on 2023-06-27T23:45:37+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shepherd-ai"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
